version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Linting
          command: npm run lint
